### ISSUE TITLE
feat : 扩展更多的选项

### ISSUE THREAD

**Issue by RSS1102** [dishait/vue-dark-switch#1]
想问下可以进行一些更多的参数扩展吗？
1. 按钮的背景
2. 按钮的icon自定义

**Comment by markthree** [comment]
@RSS1102 靓仔可以的，不过我最近在做其他的工作，可能会在未来某个时间点支持。当然也欢迎 `pr` 🫡

**Comment by RSS1102** [comment]
> 

ok，非常乐意，It's my pleasure，我完成最近工作之后会抽空尝试一下。
