### ISSUE TITLE
请问该怎么让SwitchIcon设置成默认黑色？

### ISSUE THREAD

**Issue by B1ackg0d** [dishait/vue-dark-switch#3]
如题

**Comment by markthree** [comment]
@B1ackg0d 
靓仔，支持手动切换模式 👉 [手动](https://github.com/dishait/vue-dark-switch#%E6%89%8B%E5%8A%A8)，可以按你的需求设置

**Comment by B1ackg0d** [comment]
靓仔，建议构造的时候传入默认模式，这样更优雅。
